### ISSUE TITLE
Exchanges implementation

### ISSUE THREAD

**Issue by LorenzoBettini** [LorenzoBettini/colpo#1]
- [x] single exchange
- [x] or and and exchange #8
- [x] any and all in from of Exchange #11 
- [x] any and all in to of Exchange #22
